### PR TITLE
Change SMTP server to the SCL3 internal one (#569)

### PR DESCRIPTION
**Pull request by whimboo**
This PR fixes issue #569. 

@davehunt if you have a second and could have a look? I assume it might also affect your WebQA related instances? CC'ing @stephendonner for information too.

### CODE REVIEW

**Comment by davehunt** [comment]
Is this resolved now? See [bug 1142666](https://bugzilla.mozilla.org/show_bug.cgi?id=1142666).

**Comment by whimboo** [comment]
We still need this patch. See the landed patch on the referenced bug.

**Comment by davehunt** [comment]
I wonder why this has changed without any notice? We were recently told to use smtp.mozilla.org, but I have verified this on our other Jenkins instances and made the changes. r+

**Comment by whimboo** [comment]
The change was done on [bug 1140793](https://bugzilla.mozilla.org/show_bug.cgi?id=1140793) without any notice. So as result we have to use this new server.

**Pull request merged**
