### PR TITLE
Send build_url with running job submission to TaskCluster (#788)

### PR DESCRIPTION
**Pull request by whimboo**
This PR will fix issue #788. @mjzffr can you please review?

### CODE REVIEW

**Comment by whimboo** [comment]
CC'ing @wlach for info.

**Comment by whimboo** [comment]
Here the example job: https://treeherder.allizom.org/#/jobs?repo=mozilla-central&revision=1c6385ae1fe7&filter-tier=3&selectedJob=3533300

Hm, not sure why no failures are shown in the failure summary, but only in the log viewer. @wlach any idea?

**Comment by wlach** [comment]
I'm seeing lots of failures in the failure summary for the job you linked to, am I missing something?

**Comment by whimboo** [comment]
Oh, in that case we are fine. Looks like that sometimes it takes more than 10min to populate.

**Comment by mjzffr** [comment]
@whimboo r+

**Pull request merged**
