### PR TITLE
Improve funsize updates handling via taskcluster (#627)

### PR DESCRIPTION
**Pull request by whimboo**
This PR is the first part to fix issue #627 and is doing a lot of refactoring to clean-up the code and make it more flexible for upcoming requests.

### CODE REVIEW

**Comment by AutomatedTester** [comment]
r+

**Comment by whimboo** [comment]
My testing revealed that for update messages we do not store the original taskcluster notification but the one with the single update manifest. Maybe it's not good to save the taskcluster notification because it has a limited lifetime. I would suggest to save the complete manifest instead, which contains all the locales. That way we can easier re-trigger the tests for all locales in one go, while single locales can be retriggered via the Jenkins webinterface.

**Comment by whimboo** [comment]
Thinking more about that and talking to @AutomatedTester on IRC we agreed on keeping the granular backup of manifests as what we have right now. That way build and update notifications are also handled identically.

I will update the code so --push-update-message will work. Otherwise the changes look to be working pretty good locally.

**Comment by whimboo** [comment]
The additional r+ for the latest two commits have been done via the commits directly. That's why those are not visible here after the squash.

**Pull request merged**
