### PR TITLE
virtualenv: Upgrading virtualenv rev

### PR DESCRIPTION
**Pull request by simar7**
Signed-off-by: Simarpreet Singh <s244sing@uwaterloo.ca>

### CODE REVIEW

**Comment by simar7** [comment]
Interesting... The build logs aren't clean but the it seems to pass.

SEVERE: <div class=error>Signature verification failed in downloadable &#039;hudson.tasks.Maven.MavenInstaller&#039; <a href='#' class='showDetails'>(show details)</a><pre style='display:none'>java.security.cert.CertPathValidatorException: timestamp check failed

https://travis-ci.org/mozilla/mozmill-ci/builds/48543660

**Comment by whimboo** [comment]
Btw. this PR will fix issue #207.

**Comment by whimboo** [comment]
That looks wonderful. Good to see that all is still working for us with such a large upgrade. Given that Travis is happy I will get this PR merged to master in a bit. Thanks for working on that @simar7!

**Comment by whimboo** [comment]
The PR has been merged as https://github.com/mozilla/mozmill-ci/commit/e0a599a5b0668a85302633fa4a4277b025077b69.

**Comment by whimboo** [comment]
@simar7 one helpful note for you... I would suggest that you do not work on your local master branch but create new develop branches. That way you always have a chance to re-create a branch if you messed it up. Otherwise it becomes way harder.

**Comment by simar7** [comment]
@whimboo will take note of that!

**Pull request closed without merging**
