### PR TITLE
Flip all jobs for release-mozilla-beta to Marionette (#576)

### PR DESCRIPTION
**Pull request by whimboo**
This change will allow us to run the Firefox UI tests with Firefox beta builds, and fixes another part of issue #576. @AutomatedTester can you please review it?

### CODE REVIEW

**Comment by davehunt** [comment]
r+ looks sane to me

**Comment by whimboo** [comment]
Thanks @davehunt. I had to push an small update for the production jenkins patch because index have been changed on master meanwhile. When Travis is happy I will get it merged and pushed to staging.

**Comment by whimboo** [comment]
I missed to update the new parameter name for the `BUILD_VERSION` in the pulse config files. I fixed it locally and will push to staging in a moment.

**Comment by whimboo** [comment]
Follow-up patch landed as https://github.com/mozilla/mozmill-ci/commit/7509ecaf444753c21ce52a6206260cfbb41ce6b4.

**Pull request merged**
