### PR TITLE
Use timestamp of notification if no buildid is available (#633)

### PR DESCRIPTION
**Pull request by whimboo**
This PR will fix issue #633 by using the timestamp if available for the missing buildid. With that we can find the saved log files again for retriggering jobs.

### CODE REVIEW

**Comment by davehunt** [comment]
r+ even if you decide to leave log_data as a list :)

**Comment by whimboo** [comment]
`log_data` cannot be a list because it would be immutable. That's why I had to convert it to an array. A dict would have also be possible here.

**Comment by whimboo** [comment]
Hm, not sure why the first commit is part of this PR. It's actually a different PR which already got landed. I will push an update.

**Comment by whimboo** [comment]
And sorry for the second last comment. I have only seen that one and missed the dict proposal from before. I will actually use a dict now.

**Comment by whimboo** [comment]
PR with the dict fix got merged as https://github.com/mozilla/mozmill-ci/commit/2f002150ed4b327f3b832f9b671a06086963a987. Thanks for the review @davehunt!

**Pull request closed without merging**
