### PR TITLE
Create get_mozharness job to fetch a checkout of mozharness from mozilla-central (#642)

### PR DESCRIPTION
**Pull request by whimboo**
This PR is a partial fix for issue #642 which allows @sydvicious to use mozharness for the upcoming media tests. I will wait for Travis results before asking for review given that I have strange failures locally.

### CODE REVIEW

**Comment by whimboo** [comment]
Not sure which problem we currently have with our tests but with the latest changes it passes locally for me. Lets see if Travis will be happy.

**Comment by whimboo** [comment]
@sydvicious and @mjzffr the failures we currently see seem to happen way more often now and I'm not sure why. As far as I can see its because of slow loading pages so that the elements we interact with cannot be found. At home I got a successful run. So I'm certain this has nothing to do with my changes. So you can review this PR.

**Comment by sydvicious** [comment]
This looks straightfoward enough. Assuming we get a passing travis run at some point, r+.

**Comment by whimboo** [comment]
I will raise a separate issue to strengthen the tests for Mozmill CI. Given that I got it passing locally I don't see how those failures are related to this PR. So I will get it merged now.

**Pull request merged**
