### PR TITLE
Ensure to delete all status files of jobs in post build step (#720)

### PR DESCRIPTION
**Pull request by whimboo**
This PR fixes issue #720. @sydvicious or @mjzffr can one of you please review?

### CODE REVIEW

**Comment by sydvicious** [comment]
Is it appropriate to archive these files with the jenkins archiver before the cleanup occurs? The workspace will be clean, but there will then be copies around Jenkins if we need them.

**Comment by whimboo** [comment]
The content of both is already getting printed to the build log. So I don't see any kind of dataloss here.

**Comment by whimboo** [comment]
Oh, and the archiver will run before this cleanup anyway! So the files should be safe.

**Comment by sydvicious** [comment]
@whimboo r+

**Pull request merged**
