### PR TITLE
Rename production OSX 10.7 machines to OSX 10.10 (#479)

### PR DESCRIPTION
**Pull request by whimboo**
This PR fixes issue #479 and will enable our 10.10 nodes in Mozmill CI once upgraded.

### CODE REVIEW

**Comment by whimboo** [comment]
@bobsilverberg or @sydvicious, could one of you please have a look at this PR? I would like to finally exchange our 10.7 boxes with 10.10. For machine related re-installs see [bug 1059264](https://bugzilla.mozilla.org/show_bug.cgi?id=1059264). Thanks

**Comment by bobsilverberg** [comment]
@whimboo LGTM. My only question is why keep 10.6 and remove 10.7? I was surprised to see that the versions will now be 10.6, 10.8, 10.9 and 10.10.

**Comment by whimboo** [comment]
This is based on statistics. 10.6 is used more often as 10.7, because the latter offers a free upgrade to the latest OS X release. Also people with PowerPC cores can only use 10.6 at maximum.

Thanks for the review. I will land it when the first two machines have been upgraded successfully.

**Comment by whimboo** [comment]
I pushed a follow-up commit which fixes the merge conflicts against current master. When Travis passes, I will get the PR merged and pushed to production.

**Pull request merged**
