### PR TITLE
Add jobs for Firefox 38.0 ESR release (#577)

### PR DESCRIPTION
**Pull request by whimboo**
This PR is the fix for issue #577. @sydvicious would you have time to review that? It's somewhat important because QA and especially SV are relying on that for the upcoming release. If you don't have the time please tell me and I have to find someone else. Thanks.

### CODE REVIEW

**Comment by whimboo** [comment]
When you want to review I would suggest that you check the individual commits of this PR. I tried to separate each part into its own commit for ease of reviewing.

**Comment by sydvicious** [comment]
I see inconsistent application of running 38 tests on Mac OS X 10.10 - one file has it listed; another does not. I am also curious as to why we are running against "mac" and "mac64" in the Jenkins jobs. Are we running on 32-bit configs?

**Comment by whimboo** [comment]
Regarding `mac` and `mac64`... this seem to be artifacts which we should refactor. Given that those are spread across all the tests it is something for a separate issue and PR.

**Comment by sydvicious** [comment]
@whimboo r+

**Comment by whimboo** [comment]
Thanks @sydvicious! I pushed those changes as https://github.com/mozilla/mozmill-ci/commit/356684d113f5cdb593faa72bd61ab6be3e5ce8ef.

**Pull request closed without merging**
