### PR TITLE
Stop testruns for esr31 nightly builds (#553)

### PR DESCRIPTION
**Pull request by whimboo**
This PR fixes issue #553. @AutomatedTester mind reviewing? Otherwise I will ask Bob. Thanks.

### CODE REVIEW

**Comment by whimboo** [comment]
By removing those tests we save 192 testruns in total per day (16 platforms x 3 testruns x 4 locales).

**Comment by whimboo** [comment]
I pushed a follow-up commit which brings back the testrun configs for the daily config and esr31. That should allow us at least to trigger some tests manually when it comes to a release. If it turns out this is not necessary we can fully remove it in a couple of weeks. For now I think it's better to keep it in.

**Comment by AutomatedTester** [comment]
r+

**Comment by whimboo** [comment]
@bhearsum and @nthomas-mozilla, what do you think about when we turn those tests off? At least given the case of broken updates on the esr31 nightly channel, which we have found out lately, I would keep at least the update checks enabled.

**Comment by bhearsum** [comment]
No objections here. https://bugzilla.mozilla.org/show_bug.cgi?id=725852 talks about having them partly for Mozmill testing, but also partly for build retention purposes. If we're turning off these tests I'm going to see about shutting the nightlies themselves off, too.

**Comment by bhearsum** [comment]
One more thing actually: where does "4 locales" come in? AFAICT we don't have l10n on ESR.

**Comment by whimboo** [comment]
The l10n builds might be a copy and paste failure on our side. I checked all the builds we have run this year and indeed no single localized build.

@bhearsum, given that you filed https://bugzilla.mozilla.org/show_bug.cgi?id=1135024, I assume that I can get rid of the esr31 configuration for nightly builds at all?

**Comment by bhearsum** [comment]
It's probably a good idea to wait until we reach a decision there. It's entirely possible that RelMan or someone else may think we still need to do them for other reasons.

**Comment by whimboo** [comment]
Alright. I will wait then with pushing anything esr31 related until the decision has been made.

**Comment by whimboo** [comment]
I talked with @AutomatedTester and we cannot wait until a decision has been made. We are simply understaffed and cannot devote any time to keep it maintained. So I'm going to merge this now, and push to production in a couple of days.

**Comment by whimboo** [comment]
PR has been merged as https://github.com/mozilla/mozmill-ci/commit/c6f513a2bbb925a43a42e2fb898dc37603c6ec80.

**Pull request closed without merging**
