### PR TITLE
Implement report submission to treeherder for firefox-ui-tests and nightly builds (#595)

### PR DESCRIPTION
**Pull request by whimboo**
This PR fixes issue #595. I'm creating it already given that it is mostly ready. There are only some tiny things to get added/fixed. Those will end-up as separate commits.

### CODE REVIEW

**Comment by whimboo** [comment]
All the code we need has been included now. So the submission to treeherder will work for all nightly and project builds. Releases are different so it would have to be a follow-up PR once we know how to best do it.

@AutomatedTester can you please review? Thanks.

**Comment by whimboo** [comment]
I tried to get the code running in staging but it failed to find the properties file with all the treeherder and AWS credentials. Maybe the slave is trying to get it from the local disk and not from master. :( Looks like I have to do more work on Monday, and maybe we have to pass all the credentials via job parameters.

**Comment by whimboo** [comment]
Hurray for having multiple options to include the environment variables! Looks like the one we used in the past is not that flexible and doesn't allow to load property files and scripts from the master. Making use of the other injection point I can specify to load the properties from the master and tests are working!

https://treeherder.allizom.org/#/jobs?repo=mozilla-central&revision=eaf4f9b45117&filter-job_group_symbol=Ff&filter-job_group_symbol=Fr&filter-job_group_symbol=Fu

I will make use of this feature and finish it up now to have the PR ready for review.

**Comment by whimboo** [comment]
In detail `EnvInjectBuildWrapper` does not work but `EnvInjectJobProperty` works.

**Comment by whimboo** [comment]
Results for today's Nightly build can be found [here](https://treeherder.allizom.org/#/jobs?repo=mozilla-central&revision=eaf4f9b45117&filter-job_group_symbol=Ff&filter-job_group_symbol=Fr&filter-job_group_symbol=Fu)

I should make sure that if S3 fails, we still send the report. That's what didn't happen for the OS X 10.8 machine.

**Comment by whimboo** [comment]
And results for Aurora are here: https://treeherder.allizom.org/#/jobs?repo=mozilla-aurora&revision=f23ac9d36eb5&filter-job_group_symbol=Ff&filter-job_group_symbol=Fr&filter-job_group_symbol=Fu

**Comment by AutomatedTester** [comment]
r+

**Comment by whimboo** [comment]
Thanks @AutomatedTester! I had to push another commit just to make sure we report Windows XP correctly. Otherwise I filed [bug 1178493](https://bugzilla.mozilla.org/show_bug.cgi?id=1178493) to upgrade our OS X 10.6 and 10.8 boxes to allow uploads to AWS S3.

**Pull request merged**
