### PR TITLE
Disable version check for newer pip releases (#775)

### PR DESCRIPTION
**Pull request by whimboo**
This PR will fix issue #775. @sydvicious can you please review? Thanks

### CODE REVIEW

**Comment by whimboo** [comment]
Gna, this will fail. I missed to update the jenkins patches.

**Comment by whimboo** [comment]
With the new commit this PR should pass Travis now.

**Comment by sydvicious** [comment]
@whimboo r+

**Comment by whimboo** [comment]
This landed change got backed out: https://github.com/mozilla/mozmill-ci/commit/349a9c5accff563ff9782412600492b76710cc9b. See the issue for details.

**Pull request merged**
