### PR TITLE
Update configs for OS X 10.11

### PR DESCRIPTION
**Pull request by whimboo**
This PR will fix issue #669. @davehunt or @mjzffr could one of you please have a look at? Thanks.

I tried to do micro-commits for each change. Due to the move of the dummy nodes to a dev jenkins.patch I had to do some smaller follow-ups but due to that change we won't have those massive merge conflicts if platforms are changing.

### CODE REVIEW

**Comment by mjzffr** [comment]
@whimboo I don't see any obvious issues here, but I'm not familiar with your setup so I could easily be missing something. If there is anything in particular that you'd like feedback about, please let me know.

**Comment by whimboo** [comment]
Thanks @mjzffr. We can wait until Tuesday and let @sydvicious also have a look over it. He is most likely more familiar meanwhile. Before I can push I would have to setup the OS X 10.11 host anyway.

**Comment by sydvicious** [comment]
So am I reading this correctly? We are diffing patches? Not my favorite methodology at all, but there are probably good reasons to continue to do that, so I won't hold things up.

r+

**Comment by whimboo** [comment]
Yes, we have to update patches for staging and production whenever system changes are happening. As I mentioned earlier I want to reduce the amount of confusing patch differences by getting as much as possible out of the Jenkins master config on master. Ideally patches for dev, staging, and production should only contain additions and no deletions.

**Comment by whimboo** [comment]
I squashed all commits and updated this PR. When Travis is green I will merge the PR. Once the staging OS X 10.11 box is online, I will also get it merged to staging.

**Pull request merged**
